### ISSUE TITLE
Make toolbar discernible with High Contrast Black theme

### ISSUE THREAD

**Issue by robfentress** [a11yfirst/distribution#4]
Icon buttons in toolbar stop being discernible in Windows High Contrast Mode with the Black theme.  Ideally, you would want to update the colors of the icons to use the appropriate system colors.  However, a quick workaround as a start is to set the `forced-color-adjust` CSS property to `none` to prevent system colors from being used altogether, although you'll have to tweak this a bit to completely stop all forced color styles from being applied:

```css
.cke_top, .cke_reset_all * {
      forced-color-adjust: none;
}
```
